### ISSUE TITLE
New channel

### ISSUE THREAD

**Issue by Jhon367** [balandro-tk/balandro-addon#1]
Please add the chanell of donghua https://www.chineseanime.co.in/

**Comment by darkozma** [comment]
Por el momento, no esta en nuestros planes de desarrollo, pero si quieres, puedes contribuir al proyecto creando este canal tu mismo. Toda contribución será bienvenida. Saludos.

At the moment, it is not in our development plans, but if you want, you can contribute to the project by creating this channel yourself. Every contribution will be appreciated. Best regards.
