### ISSUE TITLE
Balandro general Title search crashes all Kodi versions in Linux

### ISSUE THREAD

**Issue by fran44sanchez** [balandro-tk/balandro-addon#5]
When searching for a given title using Movie Search or Series Search  I have observed that Balandro passes very fast through all available channels in alphabetical order; then it stops at the last one, stays there for a short while and finally Kodi crashes. I have also noticed this behaviour with earlier versions of Balandro on Kodi 18, 19 and 20 on Linux computers, but not on Windows computers.

However searching for the very same title within any single channel works well in all cases.

Any help will be very welcome.

**Comment by darkozma** [comment]
ENG: I tried to reproduce the error on a linux system (Ubuntu 20.04.5 LTS) with Kodi 18.9 Leia --> The global search works well for me, both in Movie Search and in Series Search.

Please make sure you use the latest version of Balandro and its fix (currently 2.5.5 fix2).

Regards.


SPA: He intentado reproducir el error en un sistema linux (Ubuntu 20.04.5 LTS) con Kodi 18.9 Leia --> La Búsqueda Global funciona bien en mi caso, tanto en Búsqueda de Peliculas como en Búsqueda de Series.

Por favor, asegúrate de usar la última versión de Balandro y sus fix si los hay (actualmente 2.5.5 fix2).

Saludos.

**Comment by danielc123** [comment]
Ocurre lo mismo en mi sistema: Kodi se congela totalmente en el momento en que se realiza la búsqueda de canales para una película.
Detalles:
HW: Portatil con Intel i7-8565U, grafica Intel UHD 620, 16GB RAM
Distro: Ubuntu 22.04.3 LTS
Kodi: 20.2.0 (oficial)
Balandro: 3.1.02 con fix1

[CrashLog de Kodi](https://www.dropbox.com/scl/fi/d02t6yfhh3lzlhclf9se9/kodi_crashlog-20231026_114329.log?rlkey=rjrfiddkamh5pgkkme2or3amr&dl=0)

Podéis [ver un video](https://youtu.be/zep5dESj7mE) de cómo y cuando ocurre.

Entiendo que Balandro es un addon gratuito y cuenta con un soporte muy limitado, dejo aquí la información por si alguien de la comunidad encuentra alguna solución o aporten para la solución.

**Comment by darkozma** [comment]
Gracias por aportar detalles y crash log.

En este caso, si hemos podido reproducir el error en una màquina con Ubuntu 22 + Kodi20
Después de unos dias depurando, parece que tenemos localizado el bug y esta misma tarde lanzaremos una nueva versión del addon (3.1.03) con los patches que corrigen el error.

Puedes reportar en este hilo si se ha solucionado o hacerlo directamente en el canal oficial de Telegram: https://t.me/balandro_asesor

Saludos desde Balandro Team.

**Comment by danielc123** [comment]
Probada la nueva version 3.1.0.3 en mi sistma y comprobado que todo funciona perfectamente. 
Una maravilla !
Muchisimas gracias

**Comment by darkozma** [comment]
Gracias por reportar.
Procedo al cierre del hilo ya que se ha resuelto el 'issue'.

Saludos.
