### ISSUE TITLE
error "acceso denegado"

### ISSUE THREAD

**Issue by jjplano** [balandro-tk/balandro-addon#6]
hola. usé balandro durante un tiempo muy largo en mí Raspi3 con libreelec. recientemente tuve que reinstalarla completa, puse libreelec 11. balandro lo instalé desde el propio zip (no kelebek). desde entonces no puedo ver fuentes que compruebo con el navegador que están disponibles. me sale el error "no puedes ver el video porque... [servidor] acceso denegado (3ro.)" y el enlace, el cual ya comprobé en navegador que funciona sin problema. que puede haber pasado? no encuentro nada de información al respecto. ojalá puedas ayudarme, gracias!

**Comment by darkozma** [comment]
Deberías aportar un log al nivel mas alto y/o proporcionar ejemplos reales de canales que fallen.
Sin datos mas específicos, no podemos ayudar.

En este canal de Telegram puedes informarte para saber como reportar: https://t.me/balandro_asesor

Saludos.
